### ISSUE TITLE
docs examples

### ISSUE THREAD

**Issue by juicycleff** [remoteoss/json-schema-form#20]
Maybe you can make public the docs examples, that would be of help to many.

**Comment by sandrina-p** [comment]
Hi @juicycleff !

It's true, the doc are not public yet. Let me quote our [CONTRIBUTING](https://github.com/remoteoss/json-schema-form/blob/main/CONTRIBUTING.md).

> You can visit the [docs website](https://json-schema-form.vercel.app/), however its source is not in the repo yet. Our docs are still coupled to Remote's internal Design System and integration tests. The effort to decouple it at the moment is too high.

The good news is that we are planning to build a Playground using just React for anyone to try this out more easily, and perhaps help contribute to the library more easily.

**Comment by sandrina-p** [comment]
Closing in favor of https://github.com/remoteoss/json-schema-form/issues/9
