### ISSUE TITLE
InitialValues Problem

### ISSUE THREAD

**Issue by js-ta** [remoteoss/json-schema-form#70]
Hi,

I am evaluating your library. Therefore I would like to prefill a form with values.

I use pass initialValues to createHeadlessForm() like this

```
export default function WithReact() {
  const { fields, handleValidation } = createHeadlessForm(jsonSchemaDemo, {
    strictInputType: false, // so you don't need to pass presentation.inputType
    initialValues: { name: "Initial value" },
  });
...
```

I can't get this to work tough with your demo on the quickstart page. The initialValue is ignored.
Is this the correct way or am I missing something?

Here is an example btw:
https://codesandbox.io/p/sandbox/json-schema-form-demo-react-forked-5sfc7d

**Comment by sandrina-p** [comment]
Hi @js-ta!

The way you are using is correct, however you found a bug in the Playground indeed, I've fixed it, check the [newest version](https://codesandbox.io/p/sandbox/json-schema-form-demo-react-igh3sk). Here's what was added there:

In the `SmartForm`, it was missing to add `initialValues` to the `getDefaultValuesFromFields()`, like this:

```diff
const [values, setValues] = useState(() =>
-    getDefaultValuesFromFields(fields)
+    getDefaultValuesFromFields(fields, initialValues)
  );
```

And then update the actual util itself `getDefaultValuesFromFields()`. Does this make sense to you?

**Comment by sandrina-p** [comment]
You might think that the initialValue should come directly from `fields`, but currently it's not how it works. `initialValues` is used for another purpose — to correctly evaluate the visibility of conditional fields. Check these [tests as example](https://github.com/remoteoss/json-schema-form/blob/main/src/tests/createHeadlessForm.test.js#L3524) (look for "when default values are provided").

**Comment by sandrina-p** [comment]
I'm marking this as solved, but feel free to comment again if you find any problem :)
