### ISSUE TITLE
Inquiry about Roadmap

### ISSUE THREAD

**Issue by haditoqio** [remoteoss/json-schema-form#72]
I've been using the library for my personal projects, and it's been excellent. I plan on using the library for a work project and was wondering if we could get some information on the future plans/roadmap for a stable release version.

Thanks!

**Comment by sandrina-p** [comment]
Hi @haditoqio!

Excellent question, nowadays JSF is way more stable than a year ago. For this year, we have prioritized these 3 features:
- Refactor the `group-array` field for something more efficient (Q3 - breaking change if you use this field)
- Deprecate [config.customProperties](https://github.com/remoteoss/json-schema-form/issues/55) in favor of a better solution (https://github.com/remoteoss/json-schema-form/pull/71)
- Add TypeScript
- Open-source a simpler Playground

**Comment by sandrina-p** [comment]
We don't foresee any other major change (not already [documented as deprecated](https://json-schema-form.vercel.app/?path=/docs/api-reference-api--docs).). @haditoqio, is there any part of JSF that you are more concerned about? :)

**Comment by sandrina-p** [comment]
I'm closing this issue, but feel free to ask follow-up questions if needed :)
